services:
  - type: web
    name: t-tech-accounting
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ttech_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
